version: "3"

services:

  mysql:
    image: mariadb:11.0
    restart: always
    command: mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_HOST=%

  redis:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - ./data/redis:/data

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    # command: python manage.py runserver 0.0.0.0:8000
    command: uvicorn fundviewer.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    env_file:
      - .env
